# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 07:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogControl', '0002_auto_20171027_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='bt1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 10, 28, 7, 10, 45, 161059)),
        ),
    ]
