# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogControl', '0003_auto_20171028_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
