# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogControl', '0005_auto_20171101_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_created',)},
        ),
    ]
