# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogControl', '0006_auto_20171101_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
