# Generated by Django 2.0.5 on 2018-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogControl', '0007_auto_20171105_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
